version: '3.5'

services:
  dcsa-cbf:
    container_name: dcsa_cbf
    build:
      .
    ports:
      - 9090:9090
    environment:
      - "DB_HOST=dcsa-test-db"
      - "DB_NAME=dcsa_cbf"
      - "DB_USER=admin"
      - "DB_PASSWORD=change_this_password"
      - "ADMIN_DB_USER=admin"
      - "ADMIN_DB_PASSWORD=change_this_password"
      - "SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-nosecurity}"
      - "SPRING_DATASOURCE_PASSWORD="
      - "ROOT_LOG_LEVEL=${ROOT_LOG_LEVEL:-INFO}"
      - "DCSA_LOG_LEVEL=${DCSA_LOG_LEVEL:-INFO}"
    logging:
      options:
        max-file: '10'
        max-size: 200k
    links:
      - dcsa-test-db:dcsa-test-db
    depends_on:
      - dcsa-test-db

  dcsa-test-db:
    image: postgres:15-alpine
    container_name: dcsa_cbf_db
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "change_this_password"
    volumes:
      - ./cbf-domain/src/main/init.db:/docker-entrypoint-initdb.d:ro
    ports:
      - 5432:5432
